version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 33062:3306
    volumes:
      - ./mysql:/var/lib/mysql